ClassBasedViewProj/ClassBasedViewProj/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('classBasedApp.urls')),
]

ClassBasedViewProj/classBasedApp/urls.py
from django.urls import path
from classBasedApp import views

app_name="classBasedApp"

urlpatterns=[
    path('',views.IndexView.as_view(),name='index'),
    path('musician_details/<pk>/',views.MusicianDetail.as_view(),name='musician_details'),
    path('add_musician/',views.AddMusician.as_view(),name='add_musician'),
    path('update_musician/<pk>/',views.UpdateMusician.as_view(),name='update_musician'),
    path('delete_musician/<pk>/',views.DeleteMusician.as_view(),name='delete_musician'),

]

ClassBasedViewProj/classBasedApp/models.py
from django.db import models
from django.urls import reverse 

# Create your models here.
class Musician(models.Model):
    
    first_name=models.CharField(max_length=30)
    last_name=models.CharField(max_length=30)
    instrument=models.CharField(max_length=30)

    def __str__(self):
        return self.first_name+ " "+self.last_name

    def get_absolute_url(self):
        return reverse('classBasedApp:index')


class Album(models.Model):
    artist=models.ForeignKey(Musician,on_delete=models.CASCADE,related_name='album_list')
    name=models.CharField(max_length=30)
    release_date=models.DateField()

    rating=(
        (1,"Worst"),
        (2,"Bad"),
        (3,"Not Bad"),
        (4,"Good"),
        (5,"Excellent !!"),
    )



    num_stars=models.IntegerField(choices=rating)

    def __str__(self):
        return self.name+ " Rating : "+str(self.num_stars)

ClassBasedViewProj/classBasedApp/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views.generic import View,TemplateView,ListView,DetailView,CreateView,UpdateView,DeleteView
from classBasedApp import models
from django.urls import reverse_lazy

# Create your views here.
class IndexView(ListView):
    context_object_name='musician_list'
    model=models.Musician
    template_name='classBasedApp/index.html'

class MusicianDetail(DetailView):
    context_object_name='musicians'
    model=models.Musician
    template_name='classBasedApp/musician_details.html'

class AddMusician(CreateView):
    fields=('first_name','last_name','instrument')
    model=models.Musician
    template_name='classBasedApp/musician_form.html'


class UpdateMusician(UpdateView):
    fields=('first_name','last_name','instrument')
    model=models.Musician
    template_name='classBasedApp/musician_form.html'

class DeleteMusician(DeleteView):
    context_object_name='musician'
    model=models.Musician
    success_url=reverse_lazy('classBasedApp:index')
    template_name='classBasedApp/delete_musician.html'



    
        

ClassBasedViewProj/templates/classBasedApp/base.html
<!DOCTYPE html>
{%load static%}
<html lang="en">
<head>
  <title>{{title}}</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="{% static "css/mystyle.css" %}">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"></script>
</head>
<body>

<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
  <div class="container-fluid">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'classBasedApp:index'%}">Home</a>
      </li>
      
      <li class="nav-item">
        <a class="nav-link" href="">Logout</a>
      </li>

      <li class="nav-item">
        <a class="nav-link" href="">Register</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'classBasedApp:add_musician'%}">Add Musician</a>
      </li>
      
   
    </ul>
  </div>
</nav>
<div class="container" style="padding-top: 20px;">
{% block body_block %}
{% endblock %}

</div>



</body>
</html>

ClassBasedViewProj/templates/classBasedApp/delete_musician.html
{% extends 'classBasedApp/base.html'%}
{% block body_block%}
<h3>Delete {{musician.first_name}} {{musician.last_name}}  ?</h3>
<form method="POST">
    {%csrf_token%}
    <input type="submit" name="submit" value="Delete" class="btn btn-danger btn-sm">
    <a href="{% url 'classBasedApp:musician_details' pk=musician.pk%}" class="btn btn-info btn-sm">Cancel</a>
</form>

{%endblock%}

ClassBasedViewProj/templates/classBasedApp/index.html
{% extends 'classBasedApp/base.html'%}
{%block body_block%}
<h3>I am from Index View</h3>
<ul>
    {%for musician in musician_list%}
    <li><a href="{% url 'classBasedApp:musician_details' pk=musician.pk %}">{{musician.first_name}} {{musician.last_name}}</a></li>
    {%endfor%}
</ul>

{%endblock%}

ClassBasedViewProj/templates/classBasedApp/musician_details.html
{% extends 'classBasedApp/base.html'%}
{%block body_block%}

<h3>Musician Details :</h3>
<p>Name :{{musicians.first_name}} {{musicians.last_name}}</p>
<p>Instruement : {{musicians.instrument}}</p>

<h3>Album </h3>
<ul>
    {%for album in musicians.album_list.all%}
    <li>{{album.name}}</li>
    {%endfor%}

</ul>
<a href="{% url 'classBasedApp:update_musician' pk=musicians.pk%}" class="btn btn-warning btn-sm">Update</a>
<br>
<a href="{% url 'classBasedApp:delete_musician' pk=musicians.pk%}" class="btn btn-danger btn-sm">Delete</a>
{%endblock%}

ClassBasedViewProj/templates/classBasedApp/musician_form.html
{% extends 'classBasedApp/base.html'%}
{% block body_block%}
{%if form.instance.pk%}
<h3>Update Musician</h3>

<form method="POST">

{{form.as_p}}
{%csrf_token%}
<input type="submit" name="submit" value="Update" class="btn btn-warning btn-sm">
</form>
{%else%}
<form method="POST">

    {{form.as_p}}
    {%csrf_token%}
    <input type="submit" name="submit" value="Add" class="btn btn-primary btn-sm">
    </form>
{%endif%}
{%endblock%}