LoginRegistration_Proj/LoginRegistration_Proj/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('loginReggApp.urls')),
]

LoginRegistration_Proj/loginReggApp/urls.py
from django.urls import path
from loginReggApp import views
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns


app_name="loginReggApp"

urlpatterns=[
    path('',views.index,name='index'),
    path('register/',views.register,name='register'),
    path('login/',views.login_page,name='login'),
    path('user_login/',views.user_login,name='user_login'),
    path('logout/',views.user_logout,name='logout'),
]
urlpatterns +=staticfiles_urlpatterns()
urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

LoginRegistration_Proj/loginReggApp/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserInfo(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)

    facebook_id=models.URLField(blank=True)
    profile_pic=models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        return self.user.username

LoginRegistration_Proj/loginReggApp/forms.py
from django import forms
from django.contrib.auth.models import User
from loginReggApp.models import UserInfo


class UserForm(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput())
    class Meta:
        model=User
        fields=('username','password','email')

class UserInfoForm(forms.ModelForm):
    class Meta:
        model=UserInfo
        fields=('facebook_id','profile_pic')

LoginRegistration_Proj/loginReggApp/views.py
from django.shortcuts import render
from django.http import HttpResponse
from loginReggApp.forms import UserForm, UserInfoForm
from django.contrib.auth.models import User
from loginReggApp.models import UserInfo

from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect,HttpResponse
from django.urls import reverse
# Create your views here.
def index(request):
    diction={}
    if request.user.is_authenticated:
        current_user=request.user
        user_id=current_user.id
        user_basic_info=User.objects.get(pk=user_id)
        user_more_info=UserInfo.objects.get(user__pk=user_id)
        diction={'user_basic_info':user_basic_info,'user_more_info':user_more_info}
    return render(request,'loginReggApp/index.html',context=diction)


def login_page(request):
    diction={}
    return render(request,'loginReggApp/login.html',context=diction)


def user_login(request):
    if request.method=='POST':
        username=request.POST.get('username')
        password=request.POST.get('password')

        user=authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('loginReggApp:index'))
            else:
                return HttpResponse("Account is not active ")
        else:
            return HttpResponse("Login details are wrong!!")
    else:
       return HttpResponseRedirect(reverse('loginReggApp:login'))
@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('loginReggApp:index'))



def register(request):
    registered=False
    if request.method=='POST':
        user_form=UserForm(data=request.POST)
        user_info_form=UserInfoForm(data=request.POST)
        if user_form.is_valid() and user_info_form.is_valid():
            user=user_form.save()
            user.set_password(user.password)
            user.save()

            user_info=user_info_form.save(commit=False)
            user_info.user=user
            if 'profile_pic' in request.FILES:
                user_info.profile_pic=request.FILES['profile_pic']
            
            user_info.save()
            registered=True

    else:
        user_form=UserForm()
        user_info_form=UserInfoForm()
    diction={'user_form':user_form,'user_info_form':user_info_form,'registered':registered}
    return render(request,'loginReggApp/register.html',context=diction)

LoginRegistration_Proj/LoginRegistration_Proj/templates/loginReggApp/base.html
<!DOCTYPE html>
{%load static%}
<html lang="en">
<head>
  <title>{{title}}</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="{% static "css/mystyle.css" %}">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"></script>
</head>
<body>

<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
  <div class="container-fluid">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'loginReggApp:index'%}">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'loginReggApp:login_page'%}">Login Form</a>
      </li>
    </ul>
  </div>
</nav>
<div class="container">
{% block body_block %}
{% endblock %}

</div>



</body>
</html>

LoginRegistration_Proj/templates/loginReggApp/base.html
<!DOCTYPE html>
{%load static%}
<html lang="en">
<head>
  <title>{{title}}</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="{% static "css/mystyle.css" %}">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"></script>
</head>
<body>

<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
  <div class="container-fluid">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'loginReggApp:index'%}">Home</a>
      </li>
      {%if user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'loginReggApp:logout'%}">Logout</a>
      </li>
      {%else%}     
      <li class="nav-item">
        <a class="nav-link" href="{% url 'loginReggApp:register'%}">Register</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'loginReggApp:login'%}">Login</a>
      </li>
      {%endif%}
    </ul>
  </div>
</nav>
<div class="container" style="padding-top: 20px;">
{% block body_block %}
{% endblock %}

</div>



</body>
</html>

LoginRegistration_Proj/templates/loginReggApp/index.html
{%extends 'loginReggApp/base.html'%}
{%load static%}
{%block body_block%}
{% if user.is_authenticated %}
<p> Hi ,{{user_basic_info.username}}</p>
<p>Your Email :{{user_basic_info.email}}</p>
<p><a href="{{user_more_info.facebook_id}}">Facebook Profile</a></p>
<img src="/media/{{user_more_info.profile_pic}}" width="200px" alt="">

{%else%}
<div class="alert alert-primary">You are not logged in</div>
{%endif%}
{%endblock%}

LoginRegistration_Proj/templates/loginReggApp/login.html
{%extends 'loginReggApp/base.html'%}
{%block body_block%}
<h3>Login Please :</h3>
<form action="{% url 'loginReggApp:user_login' %}" method="POST">
    <label for="username">Username:</label>
    <input type="text" name="username" placeholder="Enter Username " required class="form-control">
    <label for="password">Password:</label>
    <input type="password" name="password" placeholder="Enter Password " required class="form-control">
    {%csrf_token%}
    <br>
    <input type="submit" name="submit" value="Login">
</form>
{%endblock%}

LoginRegistration_Proj/templates/loginReggApp/register.html
{%extends 'loginReggApp/base.html'%}
{%load static%}
{%block body_block%}
{% if registered %}
<div class="alert alert-success">Congratulations !! Registration Successful</div>
{%else%}
<form enctype="multipart/form-data" method="POST">
    {{user_form.as_p}}
    {{user_info_form.as_p}}
    {%csrf_token%}
    <input type="submit" name="submit" value="Register">
</form>
{%endif%}
{%endblock%}