CrudProj/CrudApp/urls.py
from django.urls import path
from CrudApp import views


app_name="CrudApp"

urlpatterns=[
    path('',views.index,name='index'),
    path('add_album/',views.album_form,name='album_form'),
    path('add_musician/',views.musician_form,name='musician_form'),
    path('album_list/<int:artist_id>',views.album_list,name='album_list'),
    path('edit_artist/<int:artist_id>',views.edit_artist,name='edit_artist'),
    path('edit_album/<int:album_id>',views.edit_album, name='edit_album'),
    path('delete_album/<int:album_id>',views.delete_album ,name='delete_album'),
    path('delete_artist/<int:artist_id>',views.delete_musician, name='delete_artist'),
   
   
]

CrudProj/CrudProj/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('CrudApp.urls'))
]

CrudProj/CrudApp/models.py
from django.db import models

# Create your models here.
class Musician(models.Model):
    
    first_name=models.CharField(max_length=30)
    last_name=models.CharField(max_length=30)
    instrument=models.CharField(max_length=30)

    def __str__(self):
        return self.first_name+ " "+self.last_name

class Album(models.Model):
    artist=models.ForeignKey(Musician,on_delete=models.CASCADE)
    name=models.CharField(max_length=30)
    release_date=models.DateField()

    rating=(
        (1,"Worst"),
        (2,"Bad"),
        (3,"Not Bad"),
        (4,"Good"),
        (5,"Excellent !!"),
    )



    num_stars=models.IntegerField(choices=rating)

    def __str__(self):
        return self.name+ " Rating : "+str(self.num_stars)

CrudProj/CrudApp/forms.py
from django import forms
from django.core import validators
from CrudApp import models


class MusicianForm(forms.ModelForm):
    class Meta:
        model=models.Musician
        fields="__all__"

class AlbumForm(forms.ModelForm):
    release_date=forms.DateField(widget=forms.TextInput(attrs={'type':'date'}))
    class Meta:
        model=models.Album
        fields="__all__"

CrudProj/CrudApp/views.py
from django.shortcuts import render
from django.http import HttpResponse
from CrudApp.models import Musician,Album
from CrudApp import forms
from django.db.models import Avg

# Create your views here.
def index(request):
    musician_list=Musician.objects.order_by('first_name')
    diction={'title':"Home Page",'musicians':musician_list}
    return  render(request ,'CrudApp/index.html', context=diction)


def album_form(request):
    form=forms.AlbumForm()
    if request.method=='POST':
        form=forms.AlbumForm(request.POST)
        if form.is_valid():
            form.save(commit=True)
            return index(request)
    diction={'title':"Add Album",'album_form':form}
    return render(request,'CrudApp/album_form.html',context=diction)


def musician_form(request):
    form=forms.MusicianForm()
    if request.method=='POST':
        form=forms.MusicianForm(request.POST)
        if form.is_valid():
            form.save(commit=True)
            return index(request)

    diction={'title':"Add Musician ",'musician_form':form}
    return render(request,'CrudApp/musician_form.html',context=diction)


def album_list(request,artist_id):
    artist_info=Musician.objects.get(pk=artist_id)
    album_list=Album.objects.filter(artist=artist_id).order_by('name','release_date')
    artist_rating=Album.objects.filter(artist=artist_id).aggregate(Avg('num_stars'))
    diction={'title':"List of Albums",'artist_info':artist_info,'album_list':album_list,'artist_rating':artist_rating}
    return render(request,'CrudApp/album_list.html',context=diction)
   

def edit_artist(request,artist_id):
    artist_info=Musician.objects.get(pk=artist_id)
    form=forms.MusicianForm(instance=artist_info)
    if request.method=='POST':
        form=forms.MusicianForm(request.POST,instance=artist_info)
        if form.is_valid():
            form.save(commit=True)
            return album_list(request,artist_id)

    diction={'edit_form':form}
    return render(request,'CrudApp/edit_artist.html',context=diction)

def edit_album(request,album_id):
    album_info=Album.objects.get(pk=album_id)
    form=forms.AlbumForm(instance=album_info)

    diction={}
    if request.method=='POST':
        form=forms.AlbumForm(request.POST,instance=album_info)
        if form.is_valid():
            form.save(commit=True)
            diction.update({'success_text':"Successfully Updated !!"})


    diction.update({'edit_form':form})
    diction.update({'album_id':album_id})
    return render(request ,'CrudApp/edit_album.html', context=diction)

def delete_album(request,album_id):
    album=Album.objects.get(pk=album_id).delete()
    diction={'delete_message':"Album Deleted Successfully !!!"}
    return render(request,'CrudApp/delete.html', context=diction)

def delete_musician(request,artist_id):
    artist=Musician.objects.get(pk=artist_id).delete()
    diction={'delete_message':"Musician Deleted Successfully !!"}
    return render(request,'CrudApp/delete.html',context=diction)

CrudProj/templates/CrudApp/album_form.html
<!DOCTYPE html>
{% extends "CrudApp/base.html" %}

{% block body_block%}
<h3>Album Form </h3>
<form method="POST">
    {{album_form.as_p}}
    {%csrf_token%}
    <input type="submit" name="submit" value="Add" class="btn btn-primary btn-sm">
    </form>

{% endblock %}

CrudProj/templates/CrudApp/album_list.html
<!DOCTYPE html>
{% extends "CrudApp/base.html" %}
{%load static%}
<link rel="stylesheet" href="{% static "css/mystyle.css" %}">

{% block body_block%}

<h4>Artist Name :{{artist_info.first_name}}  {{artist_info.last_name}}</h4>
<h4>Instrument : {{artist_info.instrument}}</h4>
<h4>Artist Rating : {{artist_rating.num_stars__avg}}</h4>
<a href="{% url 'CrudApp:edit_artist' artist_id=artist_info.id%}" class="btn btn-success btn-sm">Edit</a>
<h3>List of Albums </h3>
<table class="table table-bordered">
    <tr>
        <th> Album Name</th>
        <th> Release Date </th>
        <th>Rating</th>
    </tr>
    {% for album in album_list %}
    <tr>
        <td><a href="{% url 'CrudApp:edit_album' album_id=album.id%}">{{album.name}}</a></td>
        <td>{{album.release_date|date:"M d, Y"}}</td>
        <td>{{album.num_stars}}</td>
    </tr>
    {%endfor%}
</table>
<br>
<a href="{% url 'CrudApp:delete_artist' artist_id=artist_info.id%}" onclick="return confirm('Delete Musician ?')" class="btn btn-danger btn-sm">Delete</a>

{% endblock %}

CrudProj/templates/CrudApp/base.html
<!DOCTYPE html>
{%load static%}
<html lang="en">
<head>
  <title>{{title}}</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="{% static "css/mystyle.css" %}">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"></script>
</head>
<body>

<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
  <div class="container-fluid">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'CrudApp:index'%}">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'CrudApp:musician_form'%}">Add Musician</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'CrudApp:album_form'%}">Add Album</a>
      </li>
    </ul>
  </div>
</nav>
<div class="container">
{% block body_block %}
{% endblock %}

</div>



</body>
</html>

CrudProj/templates/CrudApp/delete.html
<!DOCTYPE html>
{% extends "CrudApp/base.html" %}

{% block body_block%}
<div class="alert alert-danger">{{delete_message}}</div>
{%endblock%}

CrudProj/templates/CrudApp/edit_album.html
<!DOCTYPE html>
{% extends "CrudApp/base.html" %}
{% block body_block%}
<h4>Edit Album</h4>
{%if success_text%}
<div class="alert alert-success">{{success_text }}</div>
{%endif%}
<form method="POST">
    {{edit_form.as_p}}
    {%csrf_token%}
    <input type="submit" name="submit" value="Update" class="btn btn-success btn-sm">
</form>
<br>
<a href="{% url 'CrudApp:delete_album' album_id=album_id%}" class="btn btn-danger btn-sm" onclick="return confirm('Delete this Album ?')">Delete</a>
{%endblock%}

CrudProj/templates/CrudApp/edit_artist.html
<!DOCTYPE html>
{% extends "CrudApp/base.html" %}
{% block body_block%}
<h4>Edit Artist</h4>
<form method="POST">
{{edit_form.as_p}}
{%csrf_token%}
<input type="submit" name="submit" value="Update" class="btn btn-info btn-sm">
</form>
{%endblock%}

CrudProj/templates/CrudApp/index.html
<!DOCTYPE html>
{% extends "CrudApp/base.html" %}

{% block body_block%}
<h3>List of Musician</h3>
<ul>
    {% if musicians %}
    {% for musician in musicians %}
    <li><a href="{% url 'CrudApp:album_list' artist_id=musician.id%}"> {{musician.first_name}}  {{musician.last_name}}</a></li>

    {% endfor %}
    {% else %}
    <h4>No Musician in the list</h4>
    {% endif %}
</ul>
{% endblock %}

CrudProj/templates/CrudApp/musician_form.html
<!DOCTYPE html>
{% extends "CrudApp/base.html" %}

{% block body_block%}
<h3>I am from Musician Form</h3>
<form method="POST">
{{musician_form.as_p}}
{%csrf_token%}
<input type="submit" name="submit" value="Add" class="btn btn-primary btn-sm">
</form>
{% endblock %}      